In [7]:
import numpy as np

In [12]:
#1 The Odd Ones Out
def onlyOdd(arr):
    odds = np.array([])
    for cluster in arr:
        test = np.array([])
        test = cluster[cluster%2 != 0]
        if test.size == 3:
            odds = np.append(odds, test)
    odds = odds.reshape(int(odds.size/3), 3)
    print(odds)

In [14]:
arr = np.array([[1, 2, 3], [5, 7, 9], [2, 4, 6], [7, 7, 7]])
onlyOdd(arr)

[[5. 7. 9.]
 [7. 7. 7.]]


In [16]:
#2 Let's Play Checkers! 
def checkerboard():
    board = np.zeros((8, 8)) # Creates all zero array
    board[::2] = 1 
    count = 0
    for row in board:
        if count % 2 == 0:
            count2 = 0
            for num in row:
                if count2 % 2 != 0:
                    board[count, count2] = 0
                count2 += 1
        count += 1
    count = 0
    for row in board:
        if count % 2 != 0:
            count2 = 0
            for num in row:
                if count2 % 2 != 0:
                    board[count, count2] = 1
                count2 += 1
        count += 1
    print(board)

In [18]:
checkerboard()

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [20]:
def reverse_checkerboard():
    board = np.zeros((8, 8))
    board[::2] = 1 
    count = 0
    for row in board:
        if count % 2 == 0:
            count2 = 0
            for num in row:
                if count2 % 2 != 0:
                    board[count, count2] = 0
                count2 += 1
        count += 1
    count = 0
    for row in board:
        if count % 2 != 0:
            count2 = 0
            for num in row:
                if count2 % 2 != 0:
                    board[count, count2] = 1
                count2 += 1
        count += 1
    # Switch zeros and ones
    i = 0
    for row in board:
        j = 0
        for num in row:
            if row[j] == 0:
                board[i, j] = 1
            elif row[j] == 1:
                board[i, j] = 0
            j += 1
        i += 1
    print(board)

In [22]:
reverse_checkerboard()

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [127]:
#3 The Expanding Universe
def expansion(universe, num):
    expanded = np.array([])
    i = 0
    for word in universe: 
        spaced = " "
        for letter in word: 
            spaced = spaced + letter
            spaced = spaced + " "*num
        expanded = np.append(expanded, spaced)
        i += 1
    print (expanded)

In [129]:
universe = np.array(["galaxy", "clusters"])
expansion(universe, 4)

[' g    a    l    a    x    y    '
 ' c    l    u    s    t    e    r    s    ']


In [163]:
#4
def secondLargest(planets):
    sorted = np.sort(planets)
    values = np.array([])
    for row in sorted:
        values = np.append(values, row[1])
    print(values)

In [147]:
np.random.seed(42)
planets = np.random.randint(100, 1000, (5, 5))
print (planets)

[[202 535 960 370 206]
 [171 800 120 714 221]
 [566 314 430 558 187]
 [472 199 971 763 230]
 [761 408 869 443 591]]


In [167]:
secondLargest(planets)

[206. 171. 314. 230. 443.]
